import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, Building2, Calculator, Check, ChevronDown, Download, Gauge, LineChart, LockKeyhole, Moon, Plus, Save, ShieldCheck, Sparkles, Sun, Trash2, TrendingUp, WalletCards } from 'lucide-react';

const STRIPE_PAYMENT_LINK = 'https://buy.stripe.com/test_00w5kD3QvcjZcx82vxgQE01';
const n = v => Number(v) || 0;
const euro = (v,d=0) => Number.isFinite(v) ? `${v.toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d})} €` : '—';
const percent = v => Number.isFinite(v) ? `${v.toLocaleString('fr-FR',{maximumFractionDigits:2})} %` : '—';
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const parseNumeric=v=>String(v??'').replace(/\s/g,'').replace(',','.').replace(/[^0-9.-]/g,'');
const displayNumeric=(v,decimals=0)=>{const raw=parseNumeric(v);if(raw===''||raw==='-')return raw;const num=Number(raw);return Number.isFinite(num)?num.toLocaleString('fr-FR',{maximumFractionDigits:decimals}):raw};

const initial = {nom:'Appartement centre-ville',prix:180000,notaire:8,travaux:8000,apport:20000,taux:3.6,duree:20,assurance:.34,loyer:750,copro:80,foncier:1100,gestion:0,vacance:5,tmi:30,revente:220000};

function calculate(x){
  const prix=n(x.prix), frais=prix*n(x.notaire)/100, travaux=n(x.travaux), total=prix+frais+travaux, apport=n(x.apport), emprunt=Math.max(0,total-apport);
  const mois=Math.max(12,n(x.duree)*12), tm=n(x.taux)/1200;
  const credit=tm ? emprunt*tm/(1-Math.pow(1+tm,-mois)) : emprunt/mois;
  const ass=emprunt*n(x.assurance)/100/12, mensualite=credit+ass;
  const loyers=n(x.loyer)*12, perte=loyers*n(x.vacance)/100, gestion=loyers*n(x.gestion)/100;
  const charges=n(x.copro)*12+n(x.foncier)+perte+gestion, net=loyers-charges;
  const brute=total?loyers/total*100:0, nette=total?net/total*100:0, cash=net/12-mensualite;
  const tauxFiscal=n(x.tmi)/100+.172, micro=Math.max(0,loyers*.5)*tauxFiscal;
  const interets1=emprunt*n(x.taux)/100, amort=(prix+travaux+frais)*.85/25;
  const reel=Math.max(0,loyers-charges-interets1-amort)*tauxFiscal, eco=micro-reel;
  const cashMicro=cash-micro/12, cashReel=cash-reel/12;
  const prudent=(n(x.loyer)*.95*12*(1-clamp(n(x.vacance)+2,0,100)/100)-n(x.copro)*12-n(x.foncier)-n(x.loyer)*.95*12*n(x.gestion)/100)/12-mensualite;
  const interetsTotal=Math.max(0,credit*mois-emprunt), assuranceTotal=ass*mois;
  const capital5=Math.max(0,emprunt-credit*60+interets1*4.2), patrimoine5=n(x.revente)-capital5+cashReel*60-apport;
  const triApprox=apport>0?((Math.max(0,n(x.revente)-capital5)+cashReel*60)/apport)**(1/5)*100-100:0;
  const scoreParts={rendement:Math.round(clamp((nette/7)*25,0,25)),cashflow:Math.round(clamp(12+cash/20,0,25)),securite:Math.round(clamp(18+(prudent/35)-n(x.vacance)/3,0,25)),fiscalite:Math.round(clamp(12+eco/300,0,25))};
  const score=Object.values(scoreParts).reduce((a,b)=>a+b,0);
  const projection=Array.from({length:11},(_,year)=>{const months=year*12;const capital=Math.max(0,emprunt-credit*months+interets1*Math.max(0,year)*.84);const valeur=prix*Math.pow(1.015,year);return {year,capital,valeur,net:valeur-capital};});
  return {frais,total,emprunt,credit,ass,mensualite,loyers,charges,net,brute,nette,cash,micro,reel,eco,cashMicro,cashReel,prudent,interetsTotal,assuranceTotal,patrimoine5,triApprox,score,scoreParts,projection};
}

function Input({label,value,onChange,suffix,step=1,decimals}){const d=decimals??(String(step).includes('.')?2:0);return <label className="input"><span>{label}</span><div><input type="text" inputMode="decimal" value={displayNumeric(value,d)} onChange={e=>onChange(parseNumeric(e.target.value))} onFocus={e=>e.target.select()}/><b>{suffix}</b></div></label>}
function Select({label,value,onChange,children}){return <label className="input"><span>{label}</span><div><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select><ChevronDown size={16}/></div></label>}
function Metric({label,value,sub,tone='blue',icon}){return <div className={`metric ${tone}`}><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Row({label,value,tone}){return <div className="row"><span>{label}</span><b className={tone||''}>{value}</b></div>}

function ScoreBreakdown({parts}){const items=[['Rentabilité',parts.rendement],['Cash-flow',parts.cashflow],['Marge de sécurité',parts.securite],['Fiscalité',parts.fiscalite]];return <div className="score-breakdown">{items.map(([label,value])=><div key={label}><span>{label}</span><div className="mini-track"><i style={{width:`${value*4}%`}}/></div><b>{value}/25</b></div>)}</div>}
function ProjectionChart({points}){const w=720,h=240,pad=28;const max=Math.max(...points.flatMap(p=>[p.valeur,p.capital]),1);const xy=(v,i)=>[pad+i*(w-pad*2)/(points.length-1),h-pad-v/max*(h-pad*2)];const path=k=>points.map((p,i)=>`${i?'L':'M'} ${xy(p[k],i).join(' ')}`).join(' ');return <div className="projection-chart"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Évolution estimée de la valeur du bien et du capital restant dû"><path className="gridline" d={`M ${pad} ${h-pad} H ${w-pad}`}/><path className="line-value" d={path('valeur')}/><path className="line-debt" d={path('capital')}/>{points.filter((_,i)=>i%2===0).map((p,i)=><text key={p.year} x={xy(p.valeur,i*2)[0]} y={h-7}>{p.year} an{p.year>1?'s':''}</text>)}</svg><div className="chart-legend"><span><i className="value-dot"/>Valeur estimée</span><span><i className="debt-dot"/>Capital restant dû</span></div></div>}

function Bars({items}){const max=Math.max(...items.map(i=>Math.abs(i.value)),1);return <div className="bars">{items.map(i=><div className="bar-row" key={i.label}><span>{i.label}</span><div className="track"><i style={{width:`${Math.max(4,Math.abs(i.value)/max*100)}%`}} className={i.value<0?'negative':''}/></div><b>{euro(i.value)}</b></div>)}</div>}

export default function App(){
 const [data,setData]=useState(initial), [dark,setDark]=useState(false), [premium,setPremium]=useState(false), [saved,setSaved]=useState([]), [tab,setTab]=useState('simulation');
 const c=useMemo(()=>calculate(data),[data]);
 const update=k=>v=>setData(d=>({...d,[k]:v}));
 useEffect(()=>{const s=JSON.parse(localStorage.getItem('renta-saved')||'[]');setSaved(s);setDark(localStorage.getItem('renta-dark')==='1');if(localStorage.getItem('premium_unlocked')==='true')setPremium(true);const id=new URLSearchParams(location.search).get('session_id');if(id)fetch(`/api/verify-session?session_id=${encodeURIComponent(id)}`).then(r=>r.json()).then(x=>{if(x.paid){localStorage.setItem('premium_unlocked','true');setPremium(true)}}).finally(()=>history.replaceState({},'',location.pathname));},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('renta-dark',dark?'1':'0')},[dark]);
 const save=()=>{const next=[...saved.filter(x=>x.id!==data.id),{...data,id:data.id||crypto.randomUUID(),savedAt:new Date().toISOString()}];setSaved(next);setData(next.at(-1));localStorage.setItem('renta-saved',JSON.stringify(next));};
 const remove=id=>{const next=saved.filter(x=>x.id!==id);setSaved(next);localStorage.setItem('renta-saved',JSON.stringify(next));};
 const scoreLabel=c.score>=80?'Excellent projet':c.score>=65?'Projet solide':c.score>=50?'Projet à optimiser':'Projet risqué';
 const advice=[c.cash<0&&`Réduisez le prix d’environ ${euro(Math.abs(c.cash)*12/Math.max(c.nette/100,.01))} ou augmentez l’apport.`,c.prudent<0&&'Le scénario prudent devient négatif : prévoyez davantage de trésorerie.',c.eco>500&&`Le régime réel pourrait économiser environ ${euro(c.eco)} par an.`,c.nette>=6&&'Le rendement net est supérieur à 6 %, ce qui constitue un niveau attractif.'].filter(Boolean);
 return <div className="app">
  <header className="topbar"><a className="brand"><span><Building2 size={20}/></span>Renta Locative</a><nav><button className={tab==='simulation'?'active':''} onClick={()=>setTab('simulation')}>Simulateur</button><button className={tab==='portfolio'?'active':''} onClick={()=>setTab('portfolio')}>Mes biens <em>{saved.length}</em></button></nav><div className="top-actions"><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label="Changer le thème">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="ghost" onClick={()=>print()}><Download size={16}/> Rapport PDF</button></div></header>
  {tab==='portfolio'?<main className="portfolio page"><div className="section-head"><div><span className="eyebrow">PORTEFEUILLE</span><h1>Vos simulations sauvegardées</h1></div><button className="primary" onClick={()=>{setData({...initial,nom:'Nouveau projet'});setTab('simulation')}}><Plus size={17}/> Nouveau projet</button></div>{saved.length===0?<div className="empty"><Building2 size={40}/><h2>Aucun bien sauvegardé</h2><p>Créez votre première simulation puis cliquez sur « Sauvegarder ».</p></div>:<div className="property-grid">{saved.map(x=>{const y=calculate(x);return <article className="property" key={x.id}><div><span className={`score-mini s${Math.floor(y.score/20)}`}>{y.score}/100</span><button className="delete" onClick={()=>remove(x.id)}><Trash2 size={16}/></button></div><h3>{x.nom}</h3><p>{euro(n(x.prix))} · {n(x.loyer)} € de loyer</p><div className="property-kpis"><b>{percent(y.nette)}<small>net</small></b><b className={y.cash>=0?'good':'bad'}>{euro(y.cash)}<small>cash-flow</small></b></div><button className="secondary" onClick={()=>{setData(x);setTab('simulation')}}>Ouvrir la simulation</button></article>})}</div>}</main>:
  <>
  <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/> ANALYSE IMMOBILIÈRE INSTANTANÉE</span><h1>Votre investissement locatif est-il <em>vraiment</em> rentable ?</h1><p>Rentabilité, cash-flow, fiscalité LMNP et niveau de risque : obtenez une lecture complète avant de signer.</p><div className="hero-actions"><a href="#simulateur" className="primary">Analyser mon projet <TrendingUp size={17}/></a><span><ShieldCheck size={16}/> Données conservées sur votre appareil</span></div></div><div className="score-card"><div className="score-ring" style={{'--score':`${c.score*3.6}deg`}}><div><strong>{c.score}</strong><span>/100</span></div></div><div><small>SCORE INVESTISSEUR</small><h2>{scoreLabel}</h2><p>{c.cash>=0?'Le bien s’autofinance dans le scénario central.':'Un effort d’épargne reste nécessaire.'}</p></div></div></section>
  <main className="workspace page" id="simulateur"><section className="form-panel"><div className="panel-title"><div><Calculator size={20}/><div><span>PARAMÈTRES</span><h2>Votre projet</h2></div></div><button className="save" onClick={save}><Save size={16}/> Sauvegarder</button></div><label className="project-name"><span>Nom du projet</span><input value={data.nom} onChange={e=>update('nom')(e.target.value)}/></label>
   <fieldset><legend>Acquisition</legend><div className="inputs"><Input label="Prix d’achat" value={data.prix} onChange={update('prix')} suffix="€" step="1000"/><Input label="Frais de notaire" value={data.notaire} onChange={update('notaire')} suffix="%" step=".1"/><Input label="Travaux" value={data.travaux} onChange={update('travaux')} suffix="€" step="500"/><Input label="Apport" value={data.apport} onChange={update('apport')} suffix="€" step="1000"/></div></fieldset>
   <fieldset><legend>Financement</legend><div className="inputs"><Input label="Taux du prêt" value={data.taux} onChange={update('taux')} suffix="%" step=".05"/><Input label="Durée" value={data.duree} onChange={update('duree')} suffix="ans"/><Input label="Assurance" value={data.assurance} onChange={update('assurance')} suffix="% / an" step=".01"/></div></fieldset>
   <fieldset><legend>Location & charges</legend><div className="inputs"><Input label="Loyer mensuel" value={data.loyer} onChange={update('loyer')} suffix="€" step="10"/><Input label="Copropriété" value={data.copro} onChange={update('copro')} suffix="€ / mois" step="5"/><Input label="Taxe foncière" value={data.foncier} onChange={update('foncier')} suffix="€ / an" step="50"/><Input label="Vacance" value={data.vacance} onChange={update('vacance')} suffix="%"/><Input label="Gestion" value={data.gestion} onChange={update('gestion')} suffix="%"/><Select label="Tranche d’imposition" value={data.tmi} onChange={update('tmi')}><option value="0">0 %</option><option value="11">11 %</option><option value="30">30 %</option><option value="41">41 %</option><option value="45">45 %</option></Select></div></fieldset>
  </section>
  <section className="dashboard"><div className="metrics"><Metric label="Cash-flow mensuel" value={euro(c.cash)} sub={c.cash>=0?`+${euro(c.cash*12)} par an`:`${euro(Math.abs(c.cash))} d’effort mensuel`} tone={c.cash>=0?'green':'red'} icon={<WalletCards/>}/><Metric label="Rentabilité nette" value={percent(c.nette)} sub={`Brute : ${percent(c.brute)}`} icon={<TrendingUp/>}/><Metric label="Mensualité totale" value={euro(c.mensualite)} sub={`Emprunt : ${euro(c.emprunt)}`} tone="purple" icon={<Calculator/>}/><Metric label="Score projet" value={`${c.score}/100`} sub={scoreLabel} tone="orange" icon={<Gauge/>}/></div>
   <div className="dashboard-grid"><article className="card"><div className="card-title"><div><BarChart3/><span><small>FLUX ANNUELS</small><h3>Revenus et dépenses</h3></span></div></div><Bars items={[{label:'Loyers',value:c.loyers},{label:'Charges',value:-c.charges},{label:'Crédit',value:-c.mensualite*12},{label:'Cash-flow',value:c.cash*12}]}/></article><article className="card"><div className="card-title"><div><Calculator/><span><small>SYNTHÈSE</small><h3>Structure du projet</h3></span></div></div><Row label="Coût total" value={euro(c.total)}/><Row label="Montant emprunté" value={euro(c.emprunt)}/><Row label="Charges annuelles" value={euro(c.charges)}/><Row label="Cash-flow annuel" value={euro(c.cash*12)} tone={c.cash>=0?'good':'bad'}/></article></div><div className="dashboard-grid detail-grid"><article className="card"><div className="card-title"><div><Gauge/><span><small>LECTURE DU SCORE</small><h3>Pourquoi {c.score}/100 ?</h3></span></div></div><div className={`project-badge ${c.score>=65?'badge-good':c.score>=50?'badge-mid':'badge-risk'}`}>{c.score>=80?'Excellent':c.score>=65?'Solide':c.score>=50?'À optimiser':'Risqué'}</div><ScoreBreakdown parts={c.scoreParts}/></article><article className="card"><div className="card-title"><div><LineChart/><span><small>PROJECTION INDICATIVE</small><h3>Patrimoine sur 10 ans</h3></span></div></div><ProjectionChart points={c.projection}/><small className="chart-note">Hypothèse : valorisation du bien de 1,5 % par an. Cette projection n’est pas une garantie.</small></article></div>
   <article className="advisor card"><div className="advisor-head"><span><Sparkles/> ASSISTANT D’ANALYSE</span><b>{advice.length||1} recommandation{advice.length>1?'s':''}</b></div>{(advice.length?advice:['Le projet est équilibré. Testez aussi une baisse de loyer et une vacance plus longue.']).map((a,i)=><p key={i}><Check size={17}/>{a}</p>)}</article>
   <article className="premium card"><div className="premium-copy"><span className="eyebrow"><LockKeyhole size={14}/> ANALYSE PREMIUM</span><h2>{premium?'Votre analyse fiscale complète':'Découvrez ce que le bien vous rapportera après impôts'}</h2><p>Comparez les régimes fiscaux, testez un scénario prudent et estimez le coût complet du financement.</p></div>{premium?<div className="premium-results"><div><small>Économie fiscale potentielle</small><strong className="good">{euro(Math.max(0,c.eco))}/an</strong></div><div><small>Cash-flow après impôt — réel</small><strong className={c.cashReel>=0?'good':'bad'}>{euro(c.cashReel)}/mois</strong></div><div><small>Scénario prudent</small><strong className={c.prudent>=0?'good':'bad'}>{euro(c.prudent)}/mois</strong></div><div><small>TRI approximatif à 5 ans</small><strong>{percent(c.triApprox)}</strong></div><div><small>Intérêts estimés</small><strong>{euro(c.interetsTotal)}</strong></div><div><small>Création de valeur à 5 ans</small><strong className={c.patrimoine5>=0?'good':'bad'}>{euro(c.patrimoine5)}</strong></div></div>:<><div className="premium-teaser"><div><small>ÉCONOMIE FISCALE ESTIMÉE</small><strong>{euro(Math.max(0,c.eco))}<span>/an</span></strong><p>Soit {euro(Math.max(0,c.eco)/12)} par mois.</p></div><div className="locked-chart"><Bars items={[{label:'Micro-BIC',value:c.micro},{label:'Régime réel',value:c.reel},{label:'Économie',value:c.eco}]}/><span><LockKeyhole/> Résultats détaillés masqués</span></div></div><div className="feature-grid"><span><Check/> Comparaison micro-BIC / réel</span><span><Check/> Cash-flow après impôts</span><span><Check/> Scénario prudent</span><span><Check/> TRI et création de valeur</span><span><Check/> Coût du crédit complet</span><span><Check/> Rapport imprimable</span></div><a className="premium-cta" href={STRIPE_PAYMENT_LINK}>Voir mon analyse complète <b>4,99 €/mois</b></a><small className="reassurance"><ShieldCheck/> Paiement sécurisé Stripe · Sans engagement</small></> }</article>
  </section></main></>}
  <footer><div><Building2 size={18}/> Renta Locative</div><p>Simulation indicative. Les résultats ne remplacent pas un conseil comptable, fiscal, juridique ou bancaire personnalisé.</p></footer>
 </div>
}
